application: golapa
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: ../../static/css

- url: /js
  static_dir: ../../static/js

- url: /images
  static_dir: ../../static/images

- url: /fonts
  static_dir: ../../static/fonts

- url: /.*
  script: _go_app
